-- Phase 3 (Consent Form Builder Unification): the client-authored Notice /
-- Terms & Conditions text shown once, above the form. Plain client content —
-- never generated, never a legal template we own. Nullable: every existing
-- form reads back NULL and renders nothing extra (backward compatible).
--
-- Deliberately NOT the same thing as consent_form_rows.notice_text (each
-- row's short, one-sentence purpose justification, which feeds the real
-- versioned consent_notice_versions machinery, FR-CON-02) — that stays
-- exactly as it is. This is a separate, single, free-form block belonging to
-- the form itself.

-- Up Migration

ALTER TABLE consent_forms ADD COLUMN notice_text text;

COMMENT ON COLUMN consent_forms.notice_text IS
  'Client-authored Notice/Terms & Conditions shown once, above the form. '
  'Plain informational content the client owns — never generated by the '
  'platform. NULL until the client adds one. Distinct from each consent row''s '
  'own short notice_text, which continues to drive consent_notice_versions '
  '(FR-CON-02) unchanged.';

-- Down Migration

ALTER TABLE consent_forms DROP COLUMN IF EXISTS notice_text;
